version: '3.8'

services:
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: finalproject
            MYSQL_USER: User
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
            - ./finalproject.sql:/docker-entrypoint-initdb.d/finalproject.sql  # Mount the SQL dump file.
        ports:
            - "3306:3306"

    web:
        build: ./frontend  # Points to directory containing the Dockerfile for React app
        ports:
            - "3000:3000"  # Maps port 3000 to container port 3000
        depends_on:
            - db  # Ensures the database service starts first
        environment:
            - REACT_APP_API_URL=http://localhost:3500  # Or adjust to fit backend setup

volumes:
    db_data:
